Controllers/CityController.cs
using System.Data.SqlClient;
using System.Data;
using Microsoft.AspNetCore.Mvc;

namespace Address_books.Controllers
{
    public class CityController : Controller
    {
        private IConfiguration configuration;

        public CityController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }

        public IActionResult CityList()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_City_GETALL";
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            return View(table);
        }

        public IActionResult CityDelete(int CityID)
        {
            try
            {
                string connectionString = configuration.GetConnectionString("ConnectionString");
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    SqlCommand command = connection.CreateCommand();
                    command.CommandType = CommandType.StoredProcedure;
                    command.CommandText = "PR_City_Delete";
                    command.Parameters.Add("@ID", SqlDbType.Int).Value = CityID;

                    command.ExecuteNonQuery();
                }

                TempData["SuccessMessage"] = "City deleted successfully.";
                return RedirectToAction("CityList");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "An error occurred while deleting the city: " + ex.Message;
                return RedirectToAction("CityList");
            }
        }
    }
}

Controllers/CountryController.cs
using System.Data.SqlClient;
using System.Data;
using Microsoft.AspNetCore.Mvc;

namespace Address_books.Controllers
{
    public class CountryController : Controller
    {
        private IConfiguration configuration;

        public CountryController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }

        public IActionResult From_Country()
        {
            return View();
        }

        public IActionResult List_Country()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_Country_GETALL";
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            return View(table);
        }

        public IActionResult CountryIDDelete(int CountryID)
        {
            try
            {
                string connectionString = configuration.GetConnectionString("ConnectionString");
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    SqlCommand command = connection.CreateCommand();
                    command.CommandType = CommandType.StoredProcedure;
                    command.CommandText = "PR_Country_DELETE";
                    command.Parameters.Add("@ID", SqlDbType.Int).Value = CountryID;

                    command.ExecuteNonQuery();
                }

                TempData["SuccessMessage"] = "City deleted successfully.";
                return RedirectToAction("List_Country");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "An error occurred while deleting the city: " + ex.Message;
                return RedirectToAction("List_Country");
            }
        }
    }
}

Controllers/StateController.cs
using System.Data.SqlClient;
using System.Data;
using Microsoft.AspNetCore.Mvc;

namespace Address_books.Controllers
{
    public class StateController : Controller
    {
        private IConfiguration configuration;

        public StateController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }
        public IActionResult From_State()
        {
            return View();
        }
        public IActionResult List_State()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_State_GETALL";
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            return View(table);
        }
    }
}

Views/Country/From_Country.cshtml
@model Address_books.Models.CountryClass


<main id="main" class="main">

    <a1 source="~/assets/img/apple-touch-icon.png" text="..">sdfs</a1>

    <div class="pagetitle">
        <h1>Country Elements</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Country</a></li>
                <li class="breadcrumb-item">From</li>
            </ol>
        </nav>  
    </div><!-- End Page Title -->

    <section class="section">
        <div class="container my-5">
            <h1 class="text-center mb-4">Country Form</h1>
            <form>

                <!-- CountryName -->
                <div class="mb-3">
                    <label class="form-label">CountryName</label>
                    <input type="text" class="form-control" id="countryName" placeholder="Enter country name" asp-for="Name">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <!-- CountryCode -->
                <div class="mb-3">
                    <label for="countryCode" class="form-label">CountryCode</label>
                    <input type="text" class="form-control" id="countryCode" placeholder="Enter country code" asp-for="CountryCode">
                    <span asp-validation-for="CountryCode" class="text-danger"></span>
                </div>

                <!-- UserID -->
                <div class="mb-3">
                    <label for="userID" class="form-label">UserID</label>
                    <input type="number" class="form-control" id="userID" placeholder="Enter user ID">
                </div>

                <!-- Submit Button -->
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </section>


</main><!-- End #main -->

Views/Country/List_Country.cshtml
@model DataTable
@using System.Data

<main id="main" class="main">
    <span class="text-danger">@TempData["ErrorMessage"]</span>

    <div class="container my-5">
        <h1 class="text-center mb-4">Countries</h1>
        <table class="table table-striped table-bordered">
            <thead class="table-dark">
                <tr>
                    <th>CountryID</th>
                    <th>CountryName</th>
                    <th>CountryCode</th>
                    <th>CreationDate</th>
                    <th>Username</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (DataRow dataRow in Model.Rows)
                {
                    <tr>
                        <td>@dataRow["CountryID"]</td>
                        <td>@dataRow["CountryName"]</td>
                        <td>@dataRow["CountryCode"]</td>
                        <td>@dataRow["CreationDate"]</td>
                        <td>@dataRow["UserName"]</td>
                        <td>
                            <a asp-controller="Country" asp-action="CountryIDDelete" asp-route-CountryID="@dataRow["CountryID"]" class="btn btn-outline-danger btn-xs">
                                <i class="bi bi-x"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
        <br />

    <a asp-controller="City" asp-action="CityList">CityList</a>

    <a asp-controller="Country" asp-action="List_Country">Country list</a>

    <a asp-controller="State" asp-action="List_State">State List</a>
</main>